name: C/C++ CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3

            - name: Set up submodules
              run: |
                  git submodule init
                  git submodule update

            - name: Restore Crypto++
              id: cache-cryptopp
              uses: actions/cache/restore@v3
              with:
                  path: external/cryptopp
                  key: native-cryptopp

            - name: Set up build environment
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential libgtest-dev

            - name: Configure build
              run: |
                  ./configure

            - name: Build Crypto++
              run: make cryptopp

            - name: Save Crypto++
              id: cache-cryptopp-save
              uses: actions/cache/save@v3
              with:
                  path: external/cryptopp
                  key: ${{ steps.cache-cryptopp.outputs.cache-primary-key }}

            - name: Build Project
              run: make

            - name: Run tests
              run: make check
