name: Compile on Macintosh (intel)
on:
    push:
        branches: ["master", "build-mac"]
        paths-ignore:
            - src/.build-number
    pull_request:
        branches: ["master"]
    workflow_run:
        workflows: ["Version Increment"]
        types: ["completed"]

jobs:
    build:
        runs-on: macos-15
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Set up build environment
              run: brew install cmake

            - name: Configure
              run: cmake -S . -B build -DCMAKE_OSX_ARCHITECTURES=x86_64

            - name: Build
              run: cmake --build build

            - name: Read build number from file
              id: getbuildno
              run: echo "buildno=$(cat src/.build-number)" >> "$GITHUB_OUTPUT"

            - uses: actions/upload-artifact@v4
              with:
                name: oneway-v1.1.${{ steps.getbuildno.outputs.buildno }}-mac-intel
                path: build/oneway
